### ISSUE TITLE
p0053 basic_osyncstream's ctor implementaion is wrong

### ISSUE THREAD

**Issue by yumetodo** [PeterSommerlad/SC22WG21_Papers#12]
According yo your code, it expecting that `std::basic_ostream` has default ctor.

https://github.com/PeterSommerlad/SC22WG21_Papers/blob/143a5514f69937d63db8094bc939b8d423a68f89/workspace/p0053_basic_osyncstreambuf/src/syncstream.h#L327-L333
https://github.com/PeterSommerlad/SC22WG21_Papers/blob/143a5514f69937d63db8094bc939b8d423a68f89/workspace/p0053_basic_osyncstreambuf/src/syncstream.h#L347-L359

However, actually, `std::basic_ostream` doesn't have default ctor.
https://timsong-cpp.github.io/cppwp/n4861/ostream.cons#lib:basic_ostream,constructor

**Comment by PeterSommerlad** [comment]
How do you come to that conclusion? both constructors call a non-default base class constructor via a type alias. (reading on a phone so i might have missed something)

the code compiles and its tests run. also this is just example code not meant to be ready to steal for an implementation.

**Comment by PeterSommerlad** [comment]
fixed...
