### ISSUE TITLE
scope_exit doesn't work with function references

### ISSUE THREAD

**Issue by jwakely** [PeterSommerlad/SC22WG21_Papers#15]
I think this should be valid, but fails to compile:

```c++
void f() { }

void g() {
    std::experimental::scope_exit<void(&)()> e(f);
}
```

**Comment by PeterSommerlad** [comment]
OK, that is a test case nobody thought of, because we were thinking one would always use template argument deduction in such cases...

**Comment by PeterSommerlad** [comment]
Again, I will check with scope17 repo instead and leave this untouched

https://github.com/PeterSommerlad/scope17

**Comment by PeterSommerlad** [comment]
fixed here and in scope17 repo
